using UnityEngine;
using System.Collections.Generic;

/// <summary>
/// Representative sample extracted from Transit Empire's country progression model.
/// 
/// This component groups airports under a country and controls:
/// - country purchase price
/// - airport unlock progression
/// - development generated by airline activity
/// - regional / capital / international airport visibility
/// - reset support for save/load workflows
/// - aggregate country-level statistics
/// </summary>
public class CountryProgressionSample : MonoBehaviour
{
    [Header("Economy")]
    public string CountryName;
    public float CountryPrice;
    public float CostMultiplier = 1f;
    public float PassengerMultiplier = 1f;

    [Header("Development Progress")]
    public float RegionalProgress;
    public float CapitalProgress;
    public float InternationalProgress;

    public float RegionalThreshold;
    public float CapitalThreshold;
    public float InternationalThreshold;

    [Header("Airport Pools")]
    public List<Airport> lockedRegionalAirports = new List<Airport>();
    public List<Airport> lockedCapitalAirports = new List<Airport>();
    public List<Airport> lockedInternationalAirports = new List<Airport>();

    [Header("Global Country Data")]
    public List<Airport> allRegionalAirports = new List<Airport>();
    public List<Airport> allCapitalAirports = new List<Airport>();
    public List<Airport> allInternationalAirports = new List<Airport>();

    [Header("Runtime State")]
    public int ActiveState;
    public float TotalGenerated;
    public float AirportsOwned;
    public float AverageReputation;

    private Airport[] airports;

    void Start()
    {
        airports = GetComponentsInChildren<Airport>(true);

        CalculateCountryPrice();
        BuildLockedAirportPools();
        CacheGlobalAirportGroups();
        InitializeDevelopmentThresholds();
    }

    // ---------------------------------------------------------------------
    // Initialization
    // ---------------------------------------------------------------------

    void CalculateCountryPrice()
    {
        int airportCount = airports.Length;

        CountryPrice =
            airportCount *
            0.60f *
            500_000f *
            CostMultiplier;
    }

    void InitializeDevelopmentThresholds()
    {
        RegionalThreshold = CostMultiplier * 50_000f;
        CapitalThreshold = CostMultiplier * 150_000f;
        InternationalThreshold = CostMultiplier * 300_000f;
    }

    void CacheGlobalAirportGroups()
    {
        allRegionalAirports.Clear();
        allCapitalAirports.Clear();
        allInternationalAirports.Clear();

        foreach (Airport airport in airports)
        {
            switch (airport.airportType)
            {
                case 0:
                    allRegionalAirports.Add(airport);
                    break;

                case 1:
                    allCapitalAirports.Add(airport);
                    break;

                case 2:
                    allInternationalAirports.Add(airport);
                    break;
            }
        }
    }

    void BuildLockedAirportPools()
    {
        lockedRegionalAirports.Clear();
        lockedCapitalAirports.Clear();
        lockedInternationalAirports.Clear();

        AirportsOwned = 0;

        Airport[] countryAirports = GetComponentsInChildren<Airport>(true);

        foreach (Airport airport in countryAirports)
        {
            if (airport.IsAlreadyActive)
            {
                AirportsOwned++;
                continue;
            }

            switch (airport.airportType)
            {
                case 0:
                    lockedRegionalAirports.Add(airport);
                    break;

                case 1:
                    lockedCapitalAirports.Add(airport);
                    break;

                case 2:
                    lockedInternationalAirports.Add(airport);
                    break;
            }
        }
    }

    // ---------------------------------------------------------------------
    // Country activation
    // ---------------------------------------------------------------------

    public void ActivateCountry()
    {
        ActiveState = 1;

        BuildLockedAirportPools();

        int regionalUnlocks = Mathf.Max(
            1,
            Mathf.RoundToInt(lockedRegionalAirports.Count * 0.15f)
        );

        int capitalUnlocks = Mathf.Max(
            1,
            Mathf.RoundToInt(lockedCapitalAirports.Count * 0.10f)
        );

        int internationalUnlocks = Mathf.Max(
            1,
            Mathf.RoundToInt(lockedInternationalAirports.Count * 0.10f)
        );

        UnlockRandomAirports(lockedRegionalAirports, regionalUnlocks);
        UnlockRandomAirports(lockedCapitalAirports, capitalUnlocks);
        UnlockRandomAirports(lockedInternationalAirports, internationalUnlocks);
    }

    void UnlockRandomAirports(List<Airport> airportPool, int amount)
    {
        for (int i = 0; i < amount; i++)
            UnlockRandomAirport(airportPool);
    }

    void UnlockRandomAirport(List<Airport> airportPool, bool playSound = false)
    {
        if (airportPool.Count == 0)
            return;

        int index = Random.Range(0, airportPool.Count);

        Airport selectedAirport = airportPool[index];
        airportPool.RemoveAt(index);

        selectedAirport.MakeVisible();

        AirportsOwned++;

        if (playSound)
            AudioManager.Instance.PlayAirportSpawned();

        BuildLockedAirportPools();
    }

    // ---------------------------------------------------------------------
    // Development system
    // ---------------------------------------------------------------------

    public void AddDevelopment(float moneyGenerated)
    {
        TotalGenerated += moneyGenerated;

        RegionalProgress += moneyGenerated;
        CapitalProgress += moneyGenerated;
        InternationalProgress += moneyGenerated;

        TryUnlockRegionalAirport();
        TryUnlockCapitalAirport();
        TryUnlockInternationalAirport();
    }

    void TryUnlockRegionalAirport()
    {
        if (RegionalProgress < RegionalThreshold)
            return;

        RegionalProgress = 0f;
        RegionalThreshold *= 1.2f;

        UnlockRandomAirport(lockedRegionalAirports, playSound: true);
    }

    void TryUnlockCapitalAirport()
    {
        if (CapitalProgress < CapitalThreshold)
            return;

        CapitalProgress = 0f;
        CapitalThreshold *= 1.2f;

        UnlockRandomAirport(lockedCapitalAirports, playSound: true);
    }

    void TryUnlockInternationalAirport()
    {
        if (InternationalProgress < InternationalThreshold)
            return;

        InternationalProgress = 0f;
        InternationalThreshold *= 1.2f;

        UnlockRandomAirport(lockedInternationalAirports, playSound: true);
    }

    // ---------------------------------------------------------------------
    // Aggregates
    // ---------------------------------------------------------------------

    public void CalculateAverageReputation()
    {
        Airport[] activeAirports = GetComponentsInChildren<Airport>();

        if (activeAirports.Length == 0)
            return;

        float totalReputation = 0f;

        foreach (Airport airport in activeAirports)
            totalReputation += airport.Reputation;

        AverageReputation = totalReputation / activeAirports.Length;
    }

    public float GetRegionalProgressPercent()
    {
        return RegionalThreshold > 0f
            ? RegionalProgress / RegionalThreshold
            : 0f;
    }

    public float GetCapitalProgressPercent()
    {
        return CapitalThreshold > 0f
            ? CapitalProgress / CapitalThreshold
            : 0f;
    }

    public float GetInternationalProgressPercent()
    {
        return InternationalThreshold > 0f
            ? InternationalProgress / InternationalThreshold
            : 0f;
    }

    // ---------------------------------------------------------------------
    // Save / load reset support
    // ---------------------------------------------------------------------

    public void ResetCountry()
    {
        ActiveState = 0;

        TotalGenerated = 0f;
        AirportsOwned = 0f;
        AverageReputation = 0f;

        RegionalProgress = 0f;
        CapitalProgress = 0f;
        InternationalProgress = 0f;

        Airport[] countryAirports = GetComponentsInChildren<Airport>(true);

        foreach (Airport airport in countryAirports)
        {
            airport.loadedFromSave = false;
            airport.IsAlreadyActive = false;
            airport.IsVisible = false;
            airport.gameObject.SetActive(false);
        }

        BuildLockedAirportPools();
    }
}
